### ISSUE TITLE
Add project skeleton

### ISSUE THREAD

**Issue by dkubb** [dkubb/bot#1]
A skeleton for a Haskell project will need to be created. It is unclear whether or not we will be using Yesod, another framework or even WAI will be used for this project.

I will dump a few initial thoughts based on a discussion with @mbj so that it is captured in one place:

Initially we will need an endpoint that is notified when comments are made for a specific user in a repository. Later on we will need endpoints to receive notifications when commits are pushed to branches in repositories. Also CircleCI will be sending notifications on build status, and we will cancel any builds that are for commits which no longer descend from the parent branch (or commits that are no longer part of the branch; i.e. they have been "rebased away").

We will also want to have the project deployed to Heroku, but given this is a public repository we have to be careful to retrieve credentials from the env and not from a config file or something stored in the git repository.

@mbj Do you think we should start with a Yesod skeleton for this?

**Comment by mbj** [comment]
> Do you think we should start with a Yesod skeleton for this?

There are more light weight web frameworks in the Haskell world. But I initially had good experiences with Yesod. So I think lets go for Yesod. Its most likely the bulk of the code will be Yesod independant in modules we can reuse in the event of switching the web framework.
