### ISSUE TITLE
Add deploy to heroku button

### ISSUE THREAD

**Issue by dkubb** [dkubb/bot#5]
See: https://devcenter.heroku.com/articles/heroku-button

A button should be added to the README that will allow the application to be deployed directly to heroku.

For now, I think the application should be 1:1 to each repository that it monitors, and the repository URL can be configured in the env.

While it might be possible to make the app handle multiple repositories, that will likely require more work as well as some kind of persistence for the application configuration (and auth to allow configuration to authenticated users). I think having it be 1:1 will allow for something working to be created more quickly since we can configure everything through the env.

@mbj wdyt?

**Comment by mbj** [comment]
I think that multiple repository support can be easily build from day 1. I think we' can check in a `config/repositories.yml` that does not contain credentials.

I expect we only need one SSH key for all repositories, that would be configured as a deploy key in Github. This SSH key can be configured via the heroku env, and does not need to be checked into the repository. Same for GH / CircleCI API tokens.

I think that backfilling multi repository support later will be more a pain than with starting on multiple repositories directly.

**Comment by dkubb** [comment]
We could also have the application fetch configuration from S3. I'd rather not expose the names of our private repositories in a public git repo.

**Comment by mbj** [comment]
> We could also have the application fetch configuration from S3. I'd rather not expose the names of our private repositories in a public git repo.

Thats a good point. I thought this repository is just a "library" and for the instance of the application we have a 2nd (private) repository referencing this library here.

But this is probably more work than having an S3 configuration object. A constrained AWS keypair can be made to reduce the power of the heroku user.

**Comment by dkubb** [comment]
> I thought this repository is just a "library" and for the instance of the application we have a 2nd (private) repository referencing this library here.

I wasn't really planning on that. I mean I guess we could go that way if we find we need to break things apart. I was more or less going for a really simple application for receiving the webhook requests from github and circleci, and then delegating all the hard work to libraries.

**Comment by dkubb** [comment]
@mbj did you figure out how to deploy juju-api-hs to heroku? I wonder if it's even possible to do it with the Heroku build button and if I have to use the command line tools.

**Comment by dkubb** [comment]
@mbj I wonder if perhaps I need to specify a buildpack in the env: https://github.com/mietek/haskell-on-heroku-tutorial/blob/master/app.json#L7-L10 (?)
